name: Assign Issue to Commenter

on:
  issue_comment:
    types: [created]
    body: "assign me"

jobs:
  assign:
    runs-on: ubuntu-latest
    steps:
      - name: Assign Issue
        uses: peter-evans/assignee@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          assignee: ${{ github.event.comment.user.login }}
